spring:
  data:
    # MongoDB 配置项，对应 MongoProperties 类
    mongodb:
      host: mongo
      port: 27017
      database: springboot-lab
      username: test
      password: Passw0rd
      # 上述属性，也可以只配置 uri

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。